### ISSUE TITLE
Other plugin (GPIO Shutdown) stops working when Octolight is installed

### ISSUE THREAD

**Issue by wick3r** [gigibu5/OctoLight#29]
I would love to have both this and GPIO Shutdown work at the same time. Even if I have Octolight assigned a different pin than GPIO Shutdown, it prevents GPIO shutdown from working. Is there a fix for this?

**Comment by gigibu5** [comment]
Probably not :frowning_face:. I suspect the issue is located in the pin definition. My plugin uses the BOARD definition (aka how pins are phisically numbered) while GPIO Shutdown probably uses some other scheme. Depending on the order of the plugins import, one code segment is called earlier then the other, so the last lines of code overide the first lines. I think that's where the problem lies.
